name: build feature
on:
  push:
    branches:
      - feature-*

jobs:
  feature:
    name: build feature job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: print env vars
        run: printenv

      - name: configure git
        run: |
          git config --global user.email "github@action.com"
          git config --global user.name "Github Action"

      - name: setup node.js
        if: ${{ env.GITHUB_SERVER_URL == 'https://github.com' }}
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List the state of node modules
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list

      - name: install dependencies
        run: npm install

      - name: create prelease
        run: npm run version:next

      - name: push prerelease
        run: git push --follow-tags origin feature-extended-bashio

      - name: publish xbashio
        run: npm run package

      - name: create release for gitea
        if: ${{ hashFiles('CHANGELOG.md') != '' && env.GITHUB_SERVER_URL != 'https://github.com' }}
        uses: akkuman/gitea-release-action@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: true
          files: ./dist/*.zip

      - name: create release for github
        if: ${{ hashFiles('CHANGELOG.md') != '' && env.GITHUB_SERVER_URL == 'https://github.com1' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: true

