name: build feature
on:
  push:
    branches:
      - feature-*

jobs:
  feature:
    name: build feature job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set env vars from envrionment
        run: |
          echo "GITHUB_SERVER_URL=$GITHUB_SERVER_URL" >> $GITHUB_ENV

      - name: configure git
        run: |
          git config --global user.email "github@action.com"
          git config --global user.name "Github Action"

      - name: setup node.js
        if: ${{ env.GITHUB_SERVER_URL == 'https://github.com' }}
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm install

      - name: create prelease
        run: npm run version:next

      - name: push prerelease
        run: |
          git fetch --prune
          git pull
          git push --follow-tags origin ${{ github.ref }}



