# Copyright (c) 2024 Roland Breitschaft
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT


name: create new release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IS_PRERELEASE: "${{ contains(github.event.release.tag_name, 'next') }}"
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: create release
        if: ${{ hashFiles('CHANGELOG.md') != '' && env.GITHUB_SERVER_URL != 'https://github.com'}}
        uses: akkuman/gitea-release-action@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}

      - name: create release
        if: ${{ hashFiles('CHANGELOG.md') != '' && env.GITHUB_SERVER_URL == 'https://github.com'}}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}
